"""Store metadata and lookup tables used by the Scintilla compatibility implementation.

This module belongs to the Scintilla compatibility layer used when native QScintilla is unavailable. It helps explain how `pypad.ui.editor.scintilla_compat` is structured and where this file fits into the runtime workflow.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
import re


@dataclass(frozen=True)
class ScintillaCommandMetadata:
    """Class that implements the `ScintillaCommandMetadata` runtime behavior."""
    symbol: str
    category: str
    status: str
    args: tuple[str, ...]
    notes: str = ""

    def to_dict(self) -> dict[str, object]:
        """Execute the `to_dict` workflow."""
        return asdict(self)


_ARG_OVERRIDES: dict[str, tuple[str, ...]] = {
    "SCN_MODIFIED": ("position", "line", "text", "value", "metadata"),
    "SCN_UPDATEUI": ("position", "line", "metadata"),
    "SCN_MARGINCLICK": ("line", "margin", "metadata"),
    "SCN_DWELLSTART": ("position", "line", "metadata"),
    "SCN_DWELLEND": ("position", "line", "metadata"),
    "SCN_CHARADDED": ("position", "line", "text", "value", "metadata"),
    "SCI_SETENGINEVAR": ("index", "value"),
    "SCI_SETENGINETOGGLE": ("index", "enabled"),
    "SCI_SETENGINECHANNEL": ("channel", "value"),
    "SCI_ENGINESTATESNAPSHOT": ("target",),
    "SCI_ENGINESTATEIMPORT": ("length", "payload"),
    "SCI_ENGINESTATEDIFF": ("length", "payload", "target"),
    "SCI_GETLASTNOTIFICATION": ("target",),
    "SCI_CLEARNOTIFICATIONS": (),
}

_STATUS_OVERRIDES: dict[str, str] = {
    "SCI_SETENGINEVAR": "compat-only",
    "SCI_GETENGINEVAR": "compat-only",
    "SCI_SETENGINETOGGLE": "compat-only",
    "SCI_GETENGINETOGGLE": "compat-only",
    "SCI_SETENGINECHANNEL": "compat-only",
    "SCI_GETENGINECHANNEL": "compat-only",
    "SCI_RESETENGINESTATE": "compat-only",
    "SCI_GETENGINECHECKSUM": "compat-only",
    "SCI_GETENGINEGENERATION": "compat-only",
    "SCI_ENGINESTATESNAPSHOT": "compat-only",
    "SCI_ENGINESTATEIMPORT": "compat-only",
    "SCI_ENGINESTATEDIFF": "compat-only",
    "SCI_GETLASTNOTIFICATION": "compat-only",
    "SCI_CLEARNOTIFICATIONS": "compat-only",
    "SCI_SETSELECTIONNCARET": "compat-only",
    "SCI_SETSELECTIONNANCHOR": "compat-only",
    "SCI_GETSELECTIONNCARET": "compat-only",
    "SCI_GETSELECTIONNANCHOR": "compat-only",
    "SCI_GETSELECTIONNCARETVIRTUALSPACE": "compat-only",
    "SCI_GETSELECTIONNANCHORVIRTUALSPACE": "compat-only",
    "SCI_SETSELECTIONNCARETVIRTUALSPACE": "compat-only",
    "SCI_SETSELECTIONNANCHORVIRTUALSPACE": "compat-only",
}

_NOTES_OVERRIDES: dict[str, str] = {
    "SCN_MODIFIED": "Payload metadata includes seq, reason_flags, tokenized_reasons, range_before, range_after, before_length, and after_length.",
    "SCN_UPDATEUI": "Emitted on cursor/selection movement with selection count in metadata.",
    "SCN_MARGINCLICK": "Metadata distinguishes fold-triggered clicks from sensitive-margin clicks.",
    "SCN_DWELLSTART": "Hover dwell notification emitted after the configured dwell interval.",
    "SCN_DWELLEND": "Hover dwell end emitted on left click release when a prior dwell exists.",
    "SCN_CHARADDED": "Emitted before normal key processing for plain text input.",
    "SCI_ENGINESTATESNAPSHOT": "Serializes app-exclusive engine state for persistence and diffing.",
    "SCI_ENGINESTATEIMPORT": "Imports a prior engine snapshot generated by the compat engine.",
    "SCI_ENGINESTATEDIFF": "Returns aggregate diff counts between current engine state and a prior snapshot.",
    "SCI_GETLASTNOTIFICATION": "Returns the most recently emitted notification as JSON.",
    "SCI_CLEARNOTIFICATIONS": "Clears the compat notification log and returns the number of entries removed.",
}


def _infer_category(symbol: str) -> str:
    """Internal helper for `_infer_category`."""
    if symbol.startswith("SCN_"):
        return "notification"
    if "MARKER" in symbol:
        return "marker"
    if "MARGIN" in symbol:
        return "margin"
    if "LEX" in symbol or "STYLE" in symbol:
        return "styling"
    if "FOLD" in symbol:
        return "folding"
    if "SELECTION" in symbol or symbol in {"SCI_SETSEL", "SCI_SETSELFORE", "SCI_SETSELBACK"}:
        return "selection"
    if "ENGINE" in symbol or "NOTIFICATION" in symbol:
        return "compat-extension"
    if "AUTOC" in symbol or "CALLTIP" in symbol:
        return "autocomplete"
    return "core"


def _infer_args(symbol: str) -> tuple[str, ...]:
    """Internal helper for `_infer_args`."""
    if symbol in _ARG_OVERRIDES:
        return _ARG_OVERRIDES[symbol]
    if symbol.startswith("SCN_"):
        return ("metadata",)
    if symbol.startswith("SCI_GET"):
        return ()
    if symbol.startswith("SCI_SET"):
        return ("value",)
    return ()


def load_command_metadata() -> dict[str, ScintillaCommandMetadata]:
    """Load data required by `load_command_metadata`."""
    editor_path = Path(__file__).resolve().parent / "editor.py"
    text = editor_path.read_text(encoding="utf-8")
    symbols = sorted(set(re.findall(r"\b(?:SCI|SCN)_[A-Z0-9_]+\b", text)))
    out: dict[str, ScintillaCommandMetadata] = {}
    for symbol in symbols:
        out[symbol] = ScintillaCommandMetadata(
            symbol=symbol,
            category=_infer_category(symbol),
            status=_STATUS_OVERRIDES.get(symbol, "implemented"),
            args=_infer_args(symbol),
            notes=_NOTES_OVERRIDES.get(symbol, ""),
        )
    return out
